{% set name = "Quart-Trio" %}
{% set version = "0.11.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_').lower() }}-{{ version }}.tar.gz
  sha256: 149c9c65c2faafdf455a4461b600e1983b71e593b6f8c8b91b592bbda36cea98

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry-core >=1.0.0
  run:
    - python >={{ python_min }}
    - quart >=0.19
    - trio >=0.19.0
    - hypercorn >=0.12.0
    - exceptiongroup >=1.1.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - quart_trio

about:
  home: https://gitlab.com/pgjones/quart-trio
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Quart-Trio is an extension for Quart to support the Trio event loop
  description: |
    Quart-Trio is an extension for Quart to support the Trio event loop.
    This is an alternative to using the asyncio event loop present in the Python
    standard library and supported by default in Quart.

extra:
  recipe-maintainers:
    - dhirschfeld
    - scopatz
